### ISSUE TITLE
Reduce significant figures in digital readout

### ISSUE THREAD

**Issue by nickedwards109** [Machine-Tool-Simulator/Simulator-Web-Client#47]
Right now, the digital readout for the X position and Z position has a lot of significant figures, like 3.586495498249408

To match the actual digital readout on the lathe, those numbers should be rounded to 4 digits after the decimal place (or 1/10000 of an inch), like 3.5865

**Comment by sulljohn** [comment]
IMPT for this: it would be nice if the units displayed on the control were true to the actual dimensions of a real piece of material.  The units displayed on the display should be divided by 10 from what they are now.  It is fine that all of the code was not written divided by 10 because it is easier to think of the positioning as whole numbers.

**Comment by nickedwards109** [comment]
Looks great! Solved by 7bd5efecc29478b7bf2f1b373952691fb85c9d35
